language: r
sudo: required

# R version
r: bioc-release

# Package caching only makes sense for the release versions.
cache: packages

# Packages from Bioconductor needed
bioc_required: true

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN
r_binary_packages:
  - RUnit
  - knitr
  - rmarkdown

# Package dependencies from Bioconductor
bioc_packages:
  - GenomicAlignments
  - BiocGenerics
  - Rsamtools
  - rtracklayer
  
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
